# replace <SOURCE> with absolute path to location of reference files (demo.rds, homologs.rds, idx.annoy , ref.Rds).
# replace <DESTINATION> with absolute path to where results will go (should also have Seurat object save file)
name: azimuth
services:
    azimuth:
        stdin_open: true
        tty: true
        ports:
            - 3838:3838
        volumes:
            - <SOURCE>:/home/reference-data
            - <DESTINATION>:/home/results
        image: satijalab/azimuth:seurat5
        command: /bin/bash
